# Generated by Django 3.1.1 on 2020-11-09 19:08

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='width:270px,heigth:350px', upload_to='shopImages')),
                ('name', models.CharField(max_length=150)),
                ('category', models.CharField(choices=[('operating_theatre_equipment', 'Operating Theatre Equipment'), ('OB/GYN_equipment', 'OB/GYN Equipment'), ('Diagnostic_Equipment', 'Diagnostic Equipment'), ('Sterilizer_(Autoclave)', 'Sterilizer (Autoclave)'), ('Laboratory_Equipment', 'Laboratory Equipment'), ('X-ray_Series', 'X-ray Series'), ('In-Vitro_Diagnostics', 'In-Vitro Diagnostics'), ('Hospital_Furniture', 'Hospital Furniture'), ('Walking_Aids', 'Walking Aids'), ('First-Aid_Products', 'First-Aid Products'), ('Ophthalmic_Equipment', 'Ophthalmic Equipment'), ('Dental_Equipment', 'Dental Equipment'), ('ENT_Equipment', 'ENT Equipment'), ('Home_Care_Equipment', 'Home Care Equipment'), ('Veterinary_Equipment', 'Veterinary Equipment'), ('Medical_Consumables', 'Medical Consumables')], max_length=120)),
                ('description', models.TextField()),
                ('slug', models.SlugField(max_length=150, unique=True)),
                ('price', models.IntegerField()),
                ('datepost', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('publish', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-datepost'],
            },
        ),
        migrations.CreateModel(
            name='reviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('review', models.TextField()),
                ('date', models.DateField()),
                ('shops', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medical_equipments.shop')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
