# Generated by Django 3.1.2 on 2020-11-11 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_equipments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='category',
            field=models.CharField(choices=[('operating_theatre_equipment', 'Operating Theatre Equipment'), ('OB-GYN_equipment', 'OB/GYN Equipment'), ('Diagnostic_Equipment', 'Diagnostic Equipment'), ('Sterilizer_Autoclave', 'Sterilizer (Autoclave)'), ('Laboratory_Equipment', 'Laboratory Equipment'), ('X-ray_Series', 'X-ray Series'), ('In-Vitro_Diagnostics', 'In-Vitro Diagnostics'), ('Hospital_Furniture', 'Hospital Furniture'), ('Walking_Aids', 'Walking Aids'), ('First-Aid_Products', 'First-Aid Products'), ('Ophthalmic_Equipment', 'Ophthalmic Equipment'), ('Dental_Equipment', 'Dental Equipment'), ('ENT_Equipment', 'ENT Equipment'), ('Home_Care_Equipment', 'Home Care Equipment'), ('Veterinary_Equipment', 'Veterinary Equipment'), ('Medical_Consumables', 'Medical Consumables')], max_length=120),
        ),
        migrations.AlterField(
            model_name='shop',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
