# Generated by Django 3.1.1 on 2020-11-23 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_equipments', '0003_auto_20201123_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='category',
            field=models.CharField(choices=[('operating-theatre-equipment', 'Operating Theatre Equipment'), ('ob-gyn-equipment', 'OB/GYN Equipment'), ('diagnostic-equipment', 'Diagnostic Equipment'), ('sterilizer-autoclave', 'Sterilizer (Autoclave)'), ('laboratory-equipment', 'Laboratory Equipment'), ('x-ray-series', 'X-ray Series'), ('in-vitro-diagnostics', 'In-Vitro Diagnostics'), ('hospital-furniture', 'Hospital Furniture'), ('walking-aids', 'Walking Aids'), ('first-aid-products', 'First-Aid Products'), ('ophthalmic-equipment', 'Ophthalmic Equipment'), ('dental-equipment', 'Dental Equipment'), ('ent-equipment', 'ENT Equipment'), ('home-care-equipment', 'Home Care Equipment'), ('veterinary-equipment', 'Veterinary Equipment'), ('medical-consumables', 'Medical Consumables')], max_length=120),
        ),
    ]
