# Generated by Django 3.1.1 on 2020-11-01 12:02

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='width:270px,heigth:350px', upload_to='shopImages')),
                ('name', models.CharField(max_length=150)),
                ('category', models.CharField(choices=[('Operating Theatre Equipment', 'Operating Theatre Equipment'), ('OB/GYN Equipment', 'OB/GYN Equipment'), ('Diagnostic Equipment', 'Diagnostic Equipment'), ('Sterilizer (Autoclave)', 'Sterilizer (Autoclave)'), ('Laboratory Equipment', 'Laboratory Equipment'), ('X-ray Series', 'X-ray Series'), ('In-Vitro Diagnostics', 'In-Vitro Diagnostics'), ('Hospital Furniture', 'Hospital Furniture'), ('Walking Aids', 'Walking Aids'), ('First-Aid Products', 'First-Aid Products'), ('Ophthalmic Equipment', 'Ophthalmic Equipment'), ('Dental Equipment', 'Dental Equipment'), ('ENT Equipment', 'ENT Equipment'), ('Home Care Equipment', 'Home Care Equipment'), ('Veterinary Equipment', 'Veterinary Equipment'), ('Medical Consumables', 'Medical Consumables')], max_length=120)),
                ('description', models.TextField()),
                ('slug', models.SlugField(max_length=150, unique=True)),
                ('price', models.IntegerField()),
                ('datepost', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('publish', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-datepost'],
            },
        ),
        migrations.CreateModel(
            name='reviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('review', models.TextField()),
                ('date', models.DateField()),
                ('shops', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.shop')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
