# Generated by Django 3.1.1 on 2020-11-04 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20201102_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='category',
            field=models.CharField(choices=[('operating_theatre_equipment', 'Operating Theatre Equipment'), ('OB/GYN_equipment', 'OB/GYN Equipment'), ('Diagnostic_Equipment', 'Diagnostic Equipment'), ('Sterilizer_(Autoclave)', 'Sterilizer (Autoclave)'), ('Laboratory_Equipment', 'Laboratory Equipment'), ('X-ray_Series', 'X-ray Series'), ('In-Vitro_Diagnostics', 'In-Vitro Diagnostics'), ('Hospital_Furniture', 'Hospital Furniture'), ('Walking_Aids', 'Walking Aids'), ('First-Aid_Products', 'First-Aid Products'), ('Ophthalmic_Equipment', 'Ophthalmic Equipment'), ('Dental_Equipment', 'Dental Equipment'), ('ENT_Equipment', 'ENT Equipment'), ('Home_Care_Equipment', 'Home Care Equipment'), ('Veterinary_Equipment', 'Veterinary Equipment'), ('Medical_Consumables', 'Medical Consumables')], max_length=120),
        ),
    ]
